name: Application build

on: push

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v2
      - name: Print Current Directory
        run: pwd
      - name: List Files in Dierctory
        run: ls
      - name: Check dotnet CLI
        run: dotnet build
      - name: List Files in Directory
        run: ls VieoLibrary.Api/ -R
      - name: Check NPM
        run: npm -v
